aws_dbt_snowflake_project:
  outputs:
    dev:
      account: PQIIDDT-MM55469
      database: AIRBNB
      password: eyJraWQiOiIzOTYwMTQwMjM1NjQ0OTM4IiwiYWxnIjoiRVMyNTYifQ.eyJwIjoiMjM2MDQyNzU2OjIzNjA0Mjg4NCIsImlzcyI6IlNGOjEwMTYiLCJleHAiOjE4MTM1NjAxNTV9.D-1r4Cy19jyJ1XLdrONuF84ynyjn844CbZqy_uJtRQkSTWk_DklViS6ArlrYC1ASoK-ELopaYjORMnDMs8T8CA
      role: ACCOUNTADMIN
      schema: DBT_SCHEMA
      threads: 1
      type: snowflake
      user: SUNNY
      warehouse: COMPUTE_wh
  target: dev
